const UNIT_VACANCY_SHEET_ID = "YOUR_UNIT_VACANCY_SHEET_ID";
const RENTAL_APPLICATIONS_SHEET_ID = "YOUR_RENTAL_APPLICATIONS_SHEET_ID";
const PROPERTY_DIRECTORY_SHEET_ID = "YOUR_PROPERTY_DIRECTORY_SHEET_ID";